development:
 adapter: mysql2
 database: line2_development
 username: root
 password: root
 host: localhost
 port: ${3306}

test:
 adapter: mysql2
 database: line2_test
 username: root
 password: root
 port: ${3306}

production:
 adapter: mysql2
 database: line2_production
 username: root
 password: root
 port: ${3306}

